04-28 08:00:06 database: close
org.h2.message.DbException: IO Exception: "java.io.IOException: An unexpected network error occurred"; "F:/workspaces/ZendFramework2/.metadata/.plugins/org.eclipse.dltk.core.index.sql.h2/model.h2.db"; SQL statement:
SELECT ID FROM INFORMATION_SCHEMA.LOBS WHERE TABLE = ? [90031-168]
	at org.h2.message.DbException.convert(DbException.java:269)
	at org.h2.store.LobStorage.removeAllForTable(LobStorage.java:180)
	at org.h2.engine.Database.close(Database.java:1110)
	at org.h2.engine.Database.removeSession(Database.java:1028)
	at org.h2.engine.Session.close(Session.java:563)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:361)
	at org.h2.jdbcx.JdbcXAConnection.close(JdbcXAConnection.java:85)
	at org.h2.jdbcx.JdbcConnectionPool.closeConnection(JdbcConnectionPool.java:258)
	at org.h2.jdbcx.JdbcConnectionPool.dispose(JdbcConnectionPool.java:177)
	at org.eclipse.dltk.internal.core.index.sql.h2.H2DbFactory.dispose(H2DbFactory.java:173)
	at org.eclipse.dltk.core.index.sql.DbFactory$1.shutdown(DbFactory.java:67)
	at org.eclipse.dltk.core.index.sql.SqlIndex.stop(SqlIndex.java:50)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:827)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:820)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:955)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:323)
	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1623)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1542)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:248)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:144)
	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:159)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: An unexpected network error occurred"; "F:/workspaces/ZendFramework2/.metadata/.plugins/org.eclipse.dltk.core.index.sql.h2/model.h2.db"; SQL statement:
SELECT ID FROM INFORMATION_SCHEMA.LOBS WHERE TABLE = ? [90031-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:158)
	at org.h2.message.DbException.convertIOException(DbException.java:315)
	at org.h2.store.FileStore.readFully(FileStore.java:278)
	at org.h2.store.PageStore.readPage(PageStore.java:1285)
	at org.h2.store.PageStore.getPage(PageStore.java:735)
	at org.h2.index.PageBtreeIndex.getPage(PageBtreeIndex.java:156)
	at org.h2.index.PageBtreeIndex.find(PageBtreeIndex.java:185)
	at org.h2.index.PageBtreeIndex.find(PageBtreeIndex.java:178)
	at org.h2.index.BaseIndex.find(BaseIndex.java:102)
	at org.h2.index.IndexCursor.find(IndexCursor.java:145)
	at org.h2.table.TableFilter.next(TableFilter.java:322)
	at org.h2.command.dml.Select.queryFlat(Select.java:513)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
	at org.h2.store.LobStorage.removeAllForTable(LobStorage.java:174)
	... 27 more
Caused by: java.io.IOException: An unexpected network error occurred
	at java.io.RandomAccessFile.readBytes(Native Method)
	at java.io.RandomAccessFile.read(Unknown Source)
	at org.h2.store.fs.FileDisk.read(FilePathDisk.java:424)
	at org.h2.store.fs.FileUtils.readFully(FileUtils.java:357)
	at org.h2.store.FileStore.readFully(FileStore.java:276)
	... 44 more
04-28 08:00:06 database: close
org.h2.message.DbException: IO Exception: "java.io.IOException: An unexpected network error occurred"; "F:/workspaces/ZendFramework2/.metadata/.plugins/org.eclipse.dltk.core.index.sql.h2/model.h2.db" [90031-168]
	at org.h2.message.DbException.get(DbException.java:158)
	at org.h2.message.DbException.convertIOException(DbException.java:315)
	at org.h2.store.FileStore.readFully(FileStore.java:278)
	at org.h2.store.PageStore.readPage(PageStore.java:1285)
	at org.h2.store.PageStore.getPage(PageStore.java:735)
	at org.h2.index.PageDataIndex.getPage(PageDataIndex.java:226)
	at org.h2.index.PageDataIndex.writeRowCount(PageDataIndex.java:516)
	at org.h2.index.PageDataIndex.close(PageDataIndex.java:450)
	at org.h2.table.RegularTable.close(RegularTable.java:97)
	at org.h2.engine.Database.close(Database.java:1123)
	at org.h2.engine.Database.removeSession(Database.java:1028)
	at org.h2.engine.Session.close(Session.java:563)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:361)
	at org.h2.jdbcx.JdbcXAConnection.close(JdbcXAConnection.java:85)
	at org.h2.jdbcx.JdbcConnectionPool.closeConnection(JdbcConnectionPool.java:258)
	at org.h2.jdbcx.JdbcConnectionPool.dispose(JdbcConnectionPool.java:177)
	at org.eclipse.dltk.internal.core.index.sql.h2.H2DbFactory.dispose(H2DbFactory.java:173)
	at org.eclipse.dltk.core.index.sql.DbFactory$1.shutdown(DbFactory.java:67)
	at org.eclipse.dltk.core.index.sql.SqlIndex.stop(SqlIndex.java:50)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:827)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:820)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:955)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:323)
	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1623)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1542)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:248)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:144)
	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:159)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: An unexpected network error occurred"; "F:/workspaces/ZendFramework2/.metadata/.plugins/org.eclipse.dltk.core.index.sql.h2/model.h2.db" [90031-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 36 more
Caused by: java.io.IOException: An unexpected network error occurred
	at java.io.RandomAccessFile.readBytes(Native Method)
	at java.io.RandomAccessFile.read(Unknown Source)
	at org.h2.store.fs.FileDisk.read(FilePathDisk.java:424)
	at org.h2.store.fs.FileUtils.readFully(FileUtils.java:357)
	at org.h2.store.FileStore.readFully(FileStore.java:276)
	... 33 more
04-28 08:00:06 database: close
org.h2.message.DbException: IO Exception: "java.io.IOException: An unexpected network error occurred"; "F:/workspaces/ZendFramework2/.metadata/.plugins/org.eclipse.dltk.core.index.sql.h2/model.h2.db" [90031-168]
	at org.h2.message.DbException.get(DbException.java:158)
	at org.h2.message.DbException.convertIOException(DbException.java:315)
	at org.h2.store.FileStore.readFully(FileStore.java:278)
	at org.h2.store.PageStore.readPage(PageStore.java:1285)
	at org.h2.store.PageStore.getPage(PageStore.java:735)
	at org.h2.index.PageDataIndex.getPage(PageDataIndex.java:226)
	at org.h2.index.PageDataIndex.writeRowCount(PageDataIndex.java:516)
	at org.h2.store.PageStore.writeIndexRowCounts(PageStore.java:404)
	at org.h2.store.PageStore.checkpoint(PageStore.java:427)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1196)
	at org.h2.engine.Database.close(Database.java:1149)
	at org.h2.engine.Database.removeSession(Database.java:1028)
	at org.h2.engine.Session.close(Session.java:563)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:361)
	at org.h2.jdbcx.JdbcXAConnection.close(JdbcXAConnection.java:85)
	at org.h2.jdbcx.JdbcConnectionPool.closeConnection(JdbcConnectionPool.java:258)
	at org.h2.jdbcx.JdbcConnectionPool.dispose(JdbcConnectionPool.java:177)
	at org.eclipse.dltk.internal.core.index.sql.h2.H2DbFactory.dispose(H2DbFactory.java:173)
	at org.eclipse.dltk.core.index.sql.DbFactory$1.shutdown(DbFactory.java:67)
	at org.eclipse.dltk.core.index.sql.SqlIndex.stop(SqlIndex.java:50)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:827)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:820)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:955)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:323)
	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1623)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1542)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:248)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:144)
	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:159)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: An unexpected network error occurred"; "F:/workspaces/ZendFramework2/.metadata/.plugins/org.eclipse.dltk.core.index.sql.h2/model.h2.db" [90031-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 37 more
Caused by: java.io.IOException: An unexpected network error occurred
	at java.io.RandomAccessFile.readBytes(Native Method)
	at java.io.RandomAccessFile.read(Unknown Source)
	at org.h2.store.fs.FileDisk.read(FilePathDisk.java:424)
	at org.h2.store.fs.FileUtils.readFully(FileUtils.java:357)
	at org.h2.store.FileStore.readFully(FileStore.java:276)
	... 34 more
